name: Basic CI Checks
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Lint source
        uses: golangci/golangci-lint-action@v8.0.0
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Check out code
        uses: actions/checkout@v4
      - name: Format source
        run: go fmt ./...
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Check out code
        uses: actions/checkout@v4
      - name: Vet source
        run: go vet ./...
  test:
    name: Test and Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run Unit tests
        run: go test -race -covermode=atomic -coverprofile=covprofile ./...
      - name: Apply `.test_cover_ignore`
        run: grep -vFf .test_cover_ignore covprofile > tmp && mv tmp covprofile
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          file: covprofile
          format: golang
